name: Build and Deploy Project

on:
  push:
    branches:
      - main  # Ejecutar el flujo en cada push hacia la rama main
  pull_request:
    branches:
      - main  # Ejecutar el flujo cuando se haga un PR hacia la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilizar el entorno Ubuntu m치s reciente

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Acci칩n para obtener el c칩digo del repositorio

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Configurar Node.js en la versi칩n 16
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Instalar dependencias con npm

      - name: Build project
        run: npm run build  # Ejecutar el build de React

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Subir los archivos del build como artefactos (opcional)
        with:
          name: build
          path: build  # Ruta al directorio del build
